# Generated by Django 4.0.2 on 2022-03-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Дата рождения'),
        ),
    ]
