# Generated by Django 4.0.2 on 2022-03-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='category', help_text='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='name', help_text='Наименование товара')),
                ('description', models.TextField(default='description', help_text='Описание товара')),
                ('price', models.IntegerField(default=0, help_text='Цена товара')),
                ('value', models.IntegerField(default=0, help_text='Количество товара')),
                ('link', models.TextField(default='.', help_text='Ссылка на фото товара')),
                ('update_on', models.DateTimeField(auto_now=True, help_text='Время обновления записи')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Время создания записи')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category')),
            ],
        ),
    ]
