# Generated by Django 4.0.2 on 2022-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.TextField(default='', help_text='Ссылка на фото товара'),
        ),
    ]
