# Generated by Django 4.0.2 on 2022-03-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(default='', help_text='Цвет товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(default='', help_text='Наименование товара'),
        ),
    ]
