# Generated by Django 4.0.2 on 2022-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_color_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', help_text='Цвет товара', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', help_text='Наименование товара', max_length=200),
        ),
    ]
