# Generated by Django 4.0.2 on 2022-03-18 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_and_phone', models.TextField(help_text='Имя и телефон заказчика', null=True)),
                ('structure', models.TextField(default='Пусто', help_text='Состав заказа')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Стоимость заказа', max_digits=15)),
                ('address', models.CharField(help_text='Адрес доставки', max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Время создания записи')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
