# Generated by Django 4.0.2 on 2022-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_options_remove_order_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='name1', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_and_phone',
            field=models.TextField(help_text='Имя и телефон заказчика..', null=True),
        ),
    ]
