# Generated by Django 4.0.2 on 2022-03-20 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_order_first_name_alter_order_name_and_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(default='888', on_delete=django.db.models.deletion.PROTECT, related_name='phone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='id_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
