# Generated by Django 4.0.2 on 2022-03-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0006_remove_order_first_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
